# This is a basic workflow to help you get started with Actions
name: build docker image
# Controls when the action will run.
on:
  push:
    branches:
      - master
jobs:
  build-rust-and-push-docker-image:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install Rust
        run: rustup toolchain install stable
      - name: Add rust target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Install musl-tools
        run: apt-get install musl-tools
      - name: build rust
        run: cargo build -p service --target x86_64-unknown-linux-musl  --release
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_DOCKERHUB_USERNAME }}
          password: ${{ secrets.TENCENT_DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: uswccr.ccs.tencentyun.com/uniix/web_shot:latest
